name: sahaya_app
description: A basic Flutter app for Sahaya project
publish_to: 'none'

environment:
  # This line has been corrected from '3.eno' to '3.8.0'
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  # this enables Material Icons and widgets
